services:
  bff:
    build: .
    entrypoint: /bin/bash
    environment: &bff_environment
      QUARKUS_OIDC_CLIENT_CLIENT_ENABLED: "false"
      QUARKUS_OIDC_AUTH_SERVER_URL: ${ONECX_AUTH_SERVER_URL}

  svc:
    build: .
    entrypoint: /bin/bash
    environment: &svc_environment
      TKIT_SECURITY_AUTH_ENABLED: "false"
      QUARKUS_OIDC_AUTH_SERVER_URL: ${ONECX_AUTH_SERVER_URL}
      TKIT_RS_CONTEXT_TENANT-ID_MOCK_ENABLED: ${TKIT_RS_CONTEXT_TENANT-ID_MOCK_ENABLED}

  ui:
    build: .
    entrypoint: /bin/bash
    environment: &ui_environment
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      AUTH_SERVICE_CUSTOM_URL: ""
      AUTH_SERVICE_CUSTOM_MODULE_NAME: ""
      AUTH_SERVICE_CUSTOM_BFF_URL: ""

  ##############################################################
  ######### OneCX Core application services ########################
  ##############################################################
  onecx-shell-bff:
    image: ${ONECX_SHELL_BFF}
    environment:
      <<: *bff_environment
      ONECX_PERMISSIONS_ENABLED: ${ONECX_PERMISSIONS_ENABLED}
      ONECX_PERMISSIONS_CACHE_ENABLED: ${ONECX_PERMISSIONS_CACHE_ENABLED}
      ONECX_PERMISSIONS_PRODUCT_NAME: "onecx-shell"
      QUARKUS_OIDC_TOKEN_ISSUER: http://keycloak-app/realms/OneCX
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_SECURITY_AUTH_ENABLED: ${TKIT_SECURITY_AUTH_ENABLED}
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-shell-bff.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-shell-bff.rule=Host(`onecx-shell-bff`)"
    networks:
      - onecx

  onecx-shell-ui:
    image: ${ONECX_SHELL_UI}
    ports:
      - "4300:8080"
    environment:
      <<: *ui_environment

  ############### WORKSPACE ###############
  onecx-workspace-svc:
    image: ${ONECX_WORKSPACE_SVC}
    environment:
      <<: *svc_environment
      QUARKUS_DATASOURCE_USERNAME: onecx_workspace
      QUARKUS_DATASOURCE_PASSWORD: onecx_workspace
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/onecx-workspace?sslmode=disable"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-workspace-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-workspace-svc.rule=Host(`onecx-workspace-svc`)"
    networks:
      - onecx

  onecx-workspace-bff:
    image: ${ONECX_WORKSPACE_BFF}
    environment:
      <<: *bff_environment
      ONECX_PERMISSIONS_ENABLED: ${ONECX_PERMISSIONS_ENABLED}
      ONECX_PERMISSIONS_CACHE_ENABLED: ${ONECX_PERMISSIONS_CACHE_ENABLED}
      ONECX_PERMISSIONS_PRODUCT_NAME: "onecx-workspace"
      QUARKUS_OIDC_TOKEN_ISSUER: http://keycloak-app/realms/OneCX
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_SECURITY_AUTH_ENABLED: ${TKIT_SECURITY_AUTH_ENABLED}
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-workspace-bff.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-workspace-bff.rule=Host(`onecx-workspace-bff`)"
    networks:
      - onecx

  onecx-workspace-ui:
    image: ${ONECX_WORKSPACE_UI}

volumes:
  postgres:

networks:
  onecx:
