services:
  bff:
    build: .
    entrypoint: /bin/bash
    environment: &bff_environment
      QUARKUS_OIDC_CLIENT_CLIENT_ENABLED: "false"
      QUARKUS_OIDC_AUTH_SERVER_URL: ${ONECX_AUTH_SERVER_URL}

  svc:
    build: .
    entrypoint: /bin/bash
    environment: &svc_environment
      TKIT_SECURITY_AUTH_ENABLED: "false"
      QUARKUS_OIDC_AUTH_SERVER_URL: ${ONECX_AUTH_SERVER_URL}
      TKIT_RS_CONTEXT_TENANT-ID_MOCK_ENABLED: ${TKIT_RS_CONTEXT_TENANT-ID_MOCK_ENABLED}

  ui:
    build: .
    entrypoint: /bin/bash
    environment: &ui_environment
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      AUTH_SERVICE_CUSTOM_URL: ""
      AUTH_SERVICE_CUSTOM_MODULE_NAME: ""
      AUTH_SERVICE_CUSTOM_BFF_URL: ""

  ##############################################################
  ######### OneCX Core application services ########################
  ##############################################################
  onecx-shell-bff:
    image: ${ONECX_SHELL_BFF}
    environment:
      <<: *bff_environment
      ONECX_PERMISSIONS_ENABLED: ${ONECX_PERMISSIONS_ENABLED}
      ONECX_PERMISSIONS_CACHE_ENABLED: ${ONECX_PERMISSIONS_CACHE_ENABLED}
      ONECX_PERMISSIONS_PRODUCT_NAME: "onecx-shell"
      QUARKUS_OIDC_TOKEN_ISSUER: http://keycloak-app/realms/OneCX
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_SECURITY_AUTH_ENABLED: ${TKIT_SECURITY_AUTH_ENABLED}
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-shell-bff.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-shell-bff.rule=Host(`onecx-shell-bff`)"
    networks:
      - onecx

  onecx-shell-ui:
    image: ${ONECX_SHELL_UI}
    ports:
      - "4300:8080"
    environment:
      <<: *ui_environment
      BFF_URL: "http://onecx-shell-bff:8080/"
    networks:
      - onecx

  ############### WORKSPACE ###############
  onecx-workspace-svc:
    image: ${ONECX_WORKSPACE_SVC}
    environment:
      <<: *svc_environment
      QUARKUS_DATASOURCE_USERNAME: onecx_workspace
      QUARKUS_DATASOURCE_PASSWORD: onecx_workspace
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/onecx-workspace?sslmode=disable"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-workspace-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-workspace-svc.rule=Host(`onecx-workspace-svc`)"
    networks:
      - onecx

  onecx-workspace-bff:
    image: ${ONECX_WORKSPACE_BFF}
    environment:
      <<: *bff_environment
      ONECX_PERMISSIONS_ENABLED: ${ONECX_PERMISSIONS_ENABLED}
      ONECX_PERMISSIONS_CACHE_ENABLED: ${ONECX_PERMISSIONS_CACHE_ENABLED}
      ONECX_PERMISSIONS_PRODUCT_NAME: "onecx-workspace"
      QUARKUS_OIDC_TOKEN_ISSUER: http://keycloak-app/realms/OneCX
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_SECURITY_AUTH_ENABLED: ${TKIT_SECURITY_AUTH_ENABLED}
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-workspace-bff.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-workspace-bff.rule=Host(`onecx-workspace-bff`)"
    networks:
      - onecx

  onecx-workspace-ui:
    image: ${ONECX_WORKSPACE_UI}

  ############### TENANT ###############
  onecx-tenant-svc:
    image: ${ONECX_TENANT_SVC}
    environment:
      <<: *svc_environment
      QUARKUS_DATASOURCE_USERNAME: onecx_tenant
      QUARKUS_DATASOURCE_PASSWORD: onecx_tenant
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/onecx-tenant?sslmode=disable"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-tenant-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-tenant-svc.rule=Host(`onecx-tenant-svc`)"
    networks:
      - onecx

  ############### IAM ###############
  onecx-iam-kc-svc:
    image: ${ONECX_IAM_KC_SVC}
    environment:
      <<: *svc_environment
      QUARKUS_KEYCLOAK_ADMIN_CLIENT_SERVER_URL: http://keycloak-app:8080
      QUARKUS_KEYCLOAK_ADMIN_CLIENT_REALM: master
      QUARKUS_KEYCLOAK_ADMIN_CLIENT_USERNAME: admin
      QUARKUS_KEYCLOAK_ADMIN_CLIENT_PASSWORD: admin
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-iam-kc-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-iam-kc-svc.rule=Host(`onecx-iam-kc-svc`)"
    networks:
      - onecx

  ############### PERMISSION ###############
  onecx-permission-svc:
    ports:
      - "9999:8080"
    image: ${ONECX_PERMISSION_SVC}
    environment:
      <<: *svc_environment
      ONECX_TENANT_CACHE_ENABLED: ${ONECX_TENANT_CACHE_ENABLED}
      QUARKUS_REST_CLIENT_ONECX_TENANT_URL: "http://onecx-tenant-svc:8080"
      QUARKUS_DATASOURCE_USERNAME: onecx_permission
      QUARKUS_DATASOURCE_PASSWORD: onecx_permission
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/onecx-permission?sslmode=disable"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-permission-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-permission-svc.rule=Host(`onecx-permission-svc`)"
    networks:
      - onecx

  ############### PRODUCT-STORE ###############
  onecx-product-store-svc:
    image: ${ONECX_PRODUCT_STORE_SVC}
    environment:
      <<: *svc_environment
      QUARKUS_DATASOURCE_USERNAME: onecx_product_store
      QUARKUS_DATASOURCE_PASSWORD: onecx_product_store
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/onecx-product-store?sslmode=disable"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-product-store-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-product-store-svc.rule=Host(`onecx-product-store-svc`)"
    networks:
      - onecx

  ############### THEME ###############
  onecx-theme-svc:
    image: ${ONECX_THEME_SVC}
    environment:
      <<: *svc_environment
      QUARKUS_DATASOURCE_USERNAME: onecx_theme
      QUARKUS_DATASOURCE_PASSWORD: onecx_theme
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/onecx-theme?sslmode=disable"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-theme-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-theme-svc.rule=Host(`onecx-theme-svc`)"
    networks:
      - onecx

  ############### USER_PROFILE ###############
  onecx-user-profile-avatar-svc:
    image: ${ONECX_USER_PROFILE_AVATAR_SVC}
    environment:
      <<: *svc_environment
      QUARKUS_DATASOURCE_USERNAME: onecx_user_profile_avatar
      QUARKUS_DATASOURCE_PASSWORD: onecx_user_profile_avatar
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/onecx-user-profile-avatar?sslmode=disable"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-user-profile-avatar-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-user-profile-avatar-svc.rule=Host(`onecx-user-profile-avatar-svc`)"
    networks:
      - onecx

  onecx-user-profile-svc:
    image: ${ONECX_USER_PROFILE_SVC}
    environment:
      <<: *svc_environment
      QUARKUS_DATASOURCE_USERNAME: onecx_user_profile
      QUARKUS_DATASOURCE_PASSWORD: onecx_user_profile
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/onecx-user-profile?sslmode=disable"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://keycloak-app:8080/realms/OneCX/protocol/openid-connect/certs
      TKIT_LOG_JSON_ENABLED: ${JSON_LOGGER_ENABLED}
    labels:
      - "traefik.http.services.onecx-user-profile-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.onecx-user-profile-svc.rule=Host(`onecx-user-profile-svc`)"
    networks:
      - onecx

volumes:
  postgres:

networks:
  onecx:
